spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/Database/spring-practice-jpashop/data/data
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug