spring:
  datasource:
    url: jdbc:h2:tcp://localhost/../data/data
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 서버 시작시점마다 table을 새롭게 생성
#      ddl-auto: none # 서버 시작시점에 아무런 작업도 하지 않음 (=기존 데이터 그대로 이용)
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug